import os

CHROMEDRIVER_PATH = os.environ['CHROMEDRIVER_PATH']
DESIRED_DATE = os.environ['DESIRED_DATE']
DISCORD_WEBHOOK_URL_HEARTBEAT = os.environ['DISCORD_WEBHOOK_URL_HEARTBEAT']
DISCORD_WEBHOOK_URL_TICKETS = os.environ['DISCORD_WEBHOOK_URL_TICKETS']
TARGET_URL = os.environ['TARGET_URL']
